# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip
  - pdf

python:
  version: 3.7
  install:
    - requirements: requirements/dev-requirements.txt
    - requirements: requirements/requirements.txt
    - method: pip
      path: .
